server:
  port: 8080

spring:
  application:
    name: distributed-rate-limiter

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      routes:
        - id: httpbin
          uri: https://httpbin.org
          predicates:
            - Path=/httpbin/**
          filters:
            - StripPrefix=1


rate-limiter:
  capacity: 10
  refillTokens: 1
  refillDuration: 6s
  redisPrefix: rate_limit:user